### ISSUE TITLE
如何在配置中使用外部插件？

### ISSUE THREAD

**Issue by huanglong6828** [sxzz/eslint-config#109]
### Clear and concise description of the problem

感谢大佬的配置！
请问如何正确使用第三方插件，我有一点感到困惑？
这样处理不生效，请问有什么可行的方案吗？
```
import { sxzz } from '@sxzz/eslint-config'
import eslintConfigBase from '@tcfs/eslint-config-base'

export default sxzz(
  [
    {
      plugins: { eslintConfigBase }
    }
  ],
  {
    prettier: true,
    markdown: true,
    vue: true,
    unocss: false
  }
)
```

### Suggested solution

无

### Validations

- [X] Follow our [Code of Conduct](https://github.com/sxzz/.github/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guide](https://github.com/sxzz/contribute).
- [X] Check that there isn't already an issue that request the same feature to avoid creating a duplicate.

**Comment by sxzz** [comment]
`@tcfs/eslint-config-base` 本身不是 flat config，无法与 `@sxzz/eslint-config` 一起使用。
