### ISSUE TITLE
安装后以后，一直报错，无法使用。

### ISSUE THREAD

**Issue by shunichio** [sxzz/eslint-config#17]
### Describe the bug

<img width="973" alt="image" src="https://github.com/sxzz/eslint-config/assets/23553358/e7814d2d-0d38-46ec-a173-d9aef25cf7db">
<img width="559" alt="image" src="https://github.com/sxzz/eslint-config/assets/23553358/a0fcb9e1-6bc8-4094-b3d1-8210cbb67762">
<img width="907" alt="image" src="https://github.com/sxzz/eslint-config/assets/23553358/4d393f2d-8e3d-40f7-8040-547b0f7449c0">

package.json type设置为“module”也没用。

### Reproduction

暂无

### System Info

```Shell
pnpm chrome vscode eslint
```

### Used Package Manager

pnpm

### Validations

- [X] Follow our [Code of Conduct](https://github.com/sxzz/.github/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guide](https://github.com/sxzz/contribute).
- [x] Check that there isn't already an issue that reports the same bug to avoid creating a duplicate.
- [X] Check that this is a concrete bug. For Q&A, please open a GitHub Discussion instead.
- [X] The provided reproduction is a [minimal reproducible](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by sxzz** [comment]
For VSCode, we should enable `"eslint.experimental.useFlatConfig": true`

**Comment by sxzz** [comment]
Added to README
