### ISSUE TITLE
规则未生效

### ISSUE THREAD

**Issue by shunichio** [sxzz/eslint-config#34]
### Describe the bug

请问 `'unused-imports/no-unused-imports': isInEditor ? 'off' : 'error'`，这一条规则中，isInEditor 在什么情况下为 `false` ？在 import 了一个函数以后，并未使用它，鼠标焦点移入应用，vscode 失焦，规则并未生效，没有看到报错。

### Reproduction

-

### System Info

```Shell
Windows11
```

### Used Package Manager

pnpm

### Validations

- [X] Follow our [Code of Conduct](https://github.com/sxzz/.github/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guide](https://github.com/sxzz/contribute).
- [X] Check that there isn't already an issue that reports the same bug to avoid creating a duplicate.
- [X] Check that this is a concrete bug. For Q&A, please open a GitHub Discussion instead.
- [X] The provided reproduction is a [minimal reproducible](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by sxzz** [comment]
no-unused-imports 在 IDE 中 (VScode & JetBrains') 不会开启。因为它会影响开发时把没用到的 imports 删除。
