### ISSUE TITLE
Prettier ignores html-element-content-newline

### ISSUE THREAD

**Issue by Erythros** [sxzz/eslint-config#36]
There's [a rule ](https://eslint.vuejs.org/rules/singleline-html-element-content-newline.html)that can be activated for VUE for `singleline-html-element-content-newline`. I love the rule, works great with the config, but I could not make it work at all with prettier

![phpstorm64_22xOpzHzlk](https://github.com/sxzz/eslint-config/assets/2624183/1f234a1f-3aee-469a-ba36-858b89425e38)

While this is not a bug report per se, I was just wondering if you have any suggestions on how to solve this. It also adds a space before and after the content, but I guess this is less relevant right now.

Config example:

```ts
// eslint.config.js

import {sxzz} from "@sxzz/eslint-config";

export default sxzz(
    [
        {
            rules: {
                "vue/singleline-html-element-content-newline": [
                    "error",
                    {
                        ignoreWhenNoAttributes: true,
                        ignoreWhenEmpty: true,
                        ignores: ["pre", "textarea"]
                    }
                ]
            }
        }
    ],
    {vue: true, prettier: true, markdown: true, unocss: false}
);

```

**Comment by sxzz** [comment]
It conflicts with Prettier, so you can only turn it off if you need Prettier. And `eslint-plugin-prettier` has been disabled for it. https://github.com/prettier/eslint-config-prettier/blob/19826807f2d668a05bb9c29a5f6f6a6e6e3287e4/index.js#L168

So far I have no other way to resolve the conflict other than closing one of them.
