### ISSUE TITLE
[BUG] Could not fix trailing comma in jsconfig.json file

### ISSUE THREAD

**Issue by Alkaidcc** [sxzz/eslint-config#63]
### Describe the bug

How to reproduce the bug:
1. use `pnpm create vite` to create a vue+javascript project
2. pnpm add -D @sxzz/eslint-config eslint
3. add
```json
{
  "eslint.experimental.useFlatConfig": true
}
```
to `.vscode/settings.json` file
4. when I press `cmd + s` to save and fix my code, eslint can't fix trailing comma in jsconfig.json file, besides, I found out that eslint cant't fix `App.vue` as well. However it's working for `HelloWorld.vue`. It's so weird!

I can't find out the reason 😢 If you need more help information, I'm glad to help debug.

### Reproduction

https://github.com/Alkaidcc/js-repro

### System Info

```Shell
System:
    OS: macOS 14.2.1
    CPU: (8) arm64 Apple M2
    Memory: 58.58 MB / 16.00 GB
    Shell: 5.9 - /bin/zsh
  Binaries:
    Node: 20.11.0 - ~/Library/Caches/fnm_multishells/9789_1706523927230/bin/node
    Yarn: 1.22.19 - ~/Library/pnpm/yarn
    npm: 10.2.4 - ~/Library/Caches/fnm_multishells/9789_1706523927230/bin/npm
    pnpm: 8.14.0 - ~/Library/pnpm/pnpm
    bun: 1.0.25 - /opt/homebrew/bin/bun
  Browsers:
    Chrome: 121.0.6167.85
    Safari: 17.2.1
```

### Used Package Manager

npm

### Validations

- [X] Follow our [Code of Conduct](https://github.com/sxzz/.github/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guide](https://github.com/sxzz/contribute).
- [X] Check that there isn't already an issue that reports the same bug to avoid creating a duplicate.
- [X] Check that this is a concrete bug. For Q&A, please open a GitHub Discussion instead.
- [X] The provided reproduction is a [minimal reproducible](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by Alkaidcc** [comment]
```json
// jsconfig.json
{
  "compilerOptions": {
    "baseUrl": "./",
    "paths": {
      "@/*": ["src/*"], // when I press `cmd + s` to fix it, the comma won't disappear, and the error will still exist
    },
  },
  "include": ["src/**/*"],
  "exclude": ["node_modules", "dist"],
}
```

**Comment by sxzz** [comment]
Your project has no `uno.config.ts`, but you used `all` preset. Try to use `sxzz()` preset instead.

It'll detect your installed dependency and enable necessary features automatically.

**Comment by Alkaidcc** [comment]
```js
import { sxzz } from "@sxzz/eslint-config";

export default sxzz([], {
  vue: true,
  prettier: true,
  markdown: true,
});

```
When I update my eslint config, vue files work well, but `jsconfig.json` still has trailing comma warning. Did I miss something?

**Comment by Alkaidcc** [comment]
![CleanShot 2024-01-30 at 08 36 51](https://github.com/sxzz/eslint-config/assets/54631354/9cc6d517-3248-4922-bd96-30a2be47f33f)

**Comment by sxzz** [comment]
Cannot reproduce. Please hover on warning and see which extension emitted the warning.

**Comment by sxzz** [comment]
Not relate to ESLint, but VSCode settings. Maybe you can check https://github.com/microsoft/vscode/issues/102061
